
package manage.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EInvWebServiceImplService", targetNamespace = "http://impl.cxf.aisino.com/", wsdlLocation = "http://60.194.106.83:10000/CNPC_SlProj/webService/eInvWS?wsdl")
public class EInvWebServiceImplService
    extends Service
{

    private final static URL EINVWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EINVWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EINVWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.cxf.aisino.com/", "EInvWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://60.194.106.83:10000/CNPC_SlProj/webService/eInvWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EINVWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EINVWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EInvWebServiceImplService() {
        super(__getWsdlLocation(), EINVWEBSERVICEIMPLSERVICE_QNAME);
    }

    public EInvWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EINVWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public EInvWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EINVWEBSERVICEIMPLSERVICE_QNAME);
    }

    public EInvWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EINVWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public EInvWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EInvWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEInvWebService
     */
    @WebEndpoint(name = "EInvWebServiceImplPort")
    public IEInvWebService getEInvWebServiceImplPort() {
        return super.getPort(new QName("http://impl.cxf.aisino.com/", "EInvWebServiceImplPort"), IEInvWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEInvWebService
     */
    @WebEndpoint(name = "EInvWebServiceImplPort")
    public IEInvWebService getEInvWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.cxf.aisino.com/", "EInvWebServiceImplPort"), IEInvWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EINVWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EINVWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return EINVWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
